import { Assistant } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const assistantFont = Assistant({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-assistant",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistantFont.className} antialiased`}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
